### ISSUE TITLE
Playwright - Framework - episode 56

### ISSUE THREAD

**Issue by Montrail** [ortoniKC/playwright-runner-vscode-extension#1]
Could you allow this extension to be supported by the framework you mentioned in episode 56?  Currently the framework will only allow tests to be run by providing the correct environment e.g.("npx cross-env ENV=qa|dev|qaApi|devApi").   As a resolution your extension will have to set the users desired environment in order to run tests.

**Comment by ortoniKC** [comment]
Added in the latest version.
