### ISSUE TITLE
Generated RegEx not matching any tests

### ISSUE THREAD

**Issue by c-wilcox** [ortoniKC/playwright-runner-vscode-extension#2]
\> Execute Playwright Test
test('has title', async ({ page }) => {

When I click on 'Execute Playwright Test', Runner generates and executes the following:
$ **npx playwright test example.spec.ts -g "has\s+title$"**

This is the result:
**Error: No tests found**

if I modify the command like this:
$ npx playwright test example.spec.ts -g **"has title"**

This is the result:
**Running 1 test using 1 worker

  ✓  1 playwright-course\tests\example.spec.ts:3:5 › has title (762ms)

  1 passed (3.3s)**

**Comment by ortoniKC** [comment]
Fixed in the latest version
