### ISSUE TITLE
Get error when clicking on Execute Playwright Test or Execute Playwright Suite

### ISSUE THREAD

**Issue by DavidKrings** [ortoniKC/playwright-runner-vscode-extension#8]
Steps to reproduce
1. Install extension
2. Open test file (using TrueScript)
3. Click on Execute Playwright Test or Execute Playwright Suite

Result
Getting this error showing in the bottom right corner
Cannot read properties of undefined (reading 'match')

Expectation
Instead of an error get the command printed in the Terminal tab

More Info
Published
2021-10-13, 14:42:22
Last released
2024-07-28, 14:30:26
Last updated
2024-08-10, 09:58:10
Identifier
ortoni.ortoni

**Comment by ortoniKC** [comment]
Hi, can you please restart your vs code and check if it's working?

**Comment by DavidKrings** [comment]
@ortoniKC 
Restarted VS Code and also again removed and reinstalled extension, still getting the same error

**Comment by ortoniKC** [comment]
Please share the screenshot and extension configuration, it will be easier to debug.

**Comment by DavidKrings** [comment]
This is the error
![image](https://github.com/user-attachments/assets/e7368339-0cd6-48c0-90e0-5b8dfe626ddb)

Settings
![image](https://github.com/user-attachments/assets/b79a732f-c50b-49dd-8210-7ba949f95d45)

Hope this helps.

**Comment by ortoniKC** [comment]
Hi, 
I think it is related to the different version installed.

1. CTRL + , (to open settings)
2. FInd any line with ortoniPlaywrightTestRunner
3. Remove every line and add the following:

```
 "ortoniPlaywrightTestRunner.environments": {
    "No Environment": "",
  },
  "ortoniPlaywrightTestRunner.defaultEnvironment": "No Environment",
```

Then restart VS code and it should work fine.

**Comment by DavidKrings** [comment]
Sorry for the late reply. The above surely fixed it. Thank you!
